# 3. PyTorch で実装する簡単な深層学習

## 3.1 実装の概要

### 3.1.3 実装の手順
1. データの前処理
2. モデルの構築
3. モデルの学習
4. モデルの検証

## 3.2 Tensor
### 3.2.1 パッケージの確認

### 3.2.2 Tensor の生成

In [4]:
import torch

a = torch.tensor([1, 2, 3])
print(a, type(a))

tensor([1, 2, 3]) <class 'torch.Tensor'>


In [7]:
print ("--- 2次元のリストから生成 ---")
b = torch.tensor([[1,2],
                  [3,4]])
print(b)

print("--- dtypeを指定し、倍精度のTensorにする ---")
c = torch.tensor([[1, 2],
                  [3, 4]], dtype=torch.float64)
print(c)

print ("--- 0から9までの数値で初期化 ---")
d = torch.arange(0, 10)
print (d)

print ("--- 全ての値が0の、2 x 3のTensor ---")
e = torch.zeros(2, 3)
print(e)

print("--- 全ての値が乱数の、2 x 3のTensor ---")
f = torch.rand(2,3)
print(f)

print("--- Tensorの形状はsizeメソッドで取得 ---")
print(f.size())

--- 2次元のリストから生成 ---
tensor([[1, 2],
        [3, 4]])
--- dtypeを指定し、倍精度のTensorにする ---
tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)
--- 0から9までの数値で初期化 ---
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
--- 全ての値が0の、2 x 3のTensor ---
tensor([[0., 0., 0.],
        [0., 0., 0.]])
--- 全ての値が乱数の、2 x 3のTensor ---
tensor([[0.3647, 0.6477, 0.2415],
        [0.2288, 0.3025, 0.5514]])
--- Tensorの形状はsizeメソッドで取得 ---
torch.Size([2, 3])


In [8]:
# linspace()関数でTensorを生成する
print("--- -5から5までの連続値を10生成 ---")
g = torch.linspace(-5, 5, 10)
print(g)

--- -5から5までの連続値を10生成 ---
tensor([-5.0000, -3.8889, -2.7778, -1.6667, -0.5556,  0.5556,  1.6667,  2.7778,
         3.8889,  5.0000])


### 3.2.3 NumPy の配列と Tensor の相互変換

In [9]:
# NumPy の配列とTensor の相互変換
print("-- Tensor → NumPy")
a = torch.tensor([[1, 2],
                  [3, 4.]])
b = a.numpy()
print(b)

print("--- NumPy → Tensor")
c = torch.from_numpy(b)
print(c)

-- Tensor → NumPy
[[1. 2.]
 [3. 4.]]
--- NumPy → Tensor
tensor([[1., 2.],
        [3., 4.]])


### 3.2.4 範囲を指定してTensorの一部にアクセス

In [10]:
# 範囲を指定してTensorの要素にアクセス
a = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

print("--- 2つのインデックスを指定 ---")
print(a[0, 1])

print("--- 範囲を指定 ---")
print(a[1:2, :2]) 

--- 2つのインデックスを指定 ---
tensor(2)
--- 範囲を指定 ---
tensor([[4, 5]])


### 3.2.5 Tensorの演算

In [13]:
# ベクトル
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])

# 行列
c = torch.tensor([[6,5,4],
                  [3,2,1]])

print(a +3) # ベクトルとスカラーの足し算
print(a + b) # ベクトル同士の足し算
print(c + 2) # 行列とスカラーの足し算
print(c + a) # 行列とベクトルの足し算(ブロードキャスト)
print(c + c) # 行列同士の足し算

tensor([4, 5, 6])
tensor([5, 7, 9])
tensor([[8, 7, 6],
        [5, 4, 3]])
tensor([[7, 7, 7],
        [4, 4, 4]])
tensor([[12, 10,  8],
        [ 6,  4,  2]])


### 3.2.6 Tensorの形状を変換